### PR TITLE
make the list of possible quotes more readable

### PR DESCRIPTION
**Pull request by ghost**
every single possible quote is now on a separate line

makes it easier to view all of them and add new quotes

### CODE REVIEW

**Comment by etcowuh** [comment]
this pr sucks #3 is better!!!

**Comment by ghost** [comment]
> this pr sucks #3 is better!!!

10 minutes and theres already a merge conflict :sob:

**Comment by etcowuh** [comment]
yeah but mine was first so yours isnt getting merged

and im also just cooler

**Comment by ghost** [comment]
> yeah but mine was first so yours isnt getting merged
> 
> and im also just cooler

can i merge your pr into here

**Comment by etcowuh** [comment]
no i will

**Comment by aegnx** [comment]
yeah this looks good im merging
thanks lol

**Comment by etcowuh** [comment]
no merge mine!!

**Pull request merged**
